version: '2'

services:
  smm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php_sqlsrv:latest
    ports:
      - "127.0.2.4:80:80"
    volumes:
      - ./:/app
      - ./conf/default:/etc/nginx/sites-available/default
      - ./conf/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
    depends_on:
      - api
    command: ['/app/conf/run.sh']
    extra_hosts:
      - "api.smm.co.id:172.18.1.3"
    networks:
      bridge :
        ipv4_address: 172.18.1.4

  api:
    build:
      context: ../api/
      dockerfile: Dockerfile
    image: php_sqlsrv:latest
    ports:
      - "127.0.2.3:80:80"
    volumes:
      - ../api/:/app
      - ./conf/default:/etc/nginx/sites-available/default
      - ./conf/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
    depends_on:
      - db
    command: ['/app/conf/run.sh']
    networks:
      bridge:
        aliases:
          - api.smm.co.id
        ipv4_address: 172.18.1.3

  db:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    ports:
      - "127.0.2.2:1433:1433"
    volumes:
      - /srv/database/sqlsrv/data:/var/opt/mssql/data
    networks:
      bridge:
        aliases:
          - db.smm.co.id
        ipv4_address: 172.18.1.2


networks:
  bridge:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.254
